spring:
  messages: encoding=UTF-8
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false


api-key:
  kakao: ENC(jWHtySr9dp+0YpaI2DbVFAf8gOFwTZBebHK5eBUY9jOkj22ebq+vRr3olmyCSLRATsmNnE3qJck=)
  naver:
    id : ENC(f1cy+08XGRFltWMT1cBfOwnR9Ue8h0jBXLwBiDFAxXY=)
    secret : ENC(niOQadcSz2D5l1mCAr4PJFvA3W5Fh4Jb)


logging.level:
  org.hibernate.SQL: debug


